title: Hello, world! I'm Asumi Saito
description: > # this means to ignore newlines until "baseurl:"
  This is Asumi's blog. 
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://asaito333.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Asumi Saito # add your name
author-img: Asumi_headshot2.jpg # add your photo
about-author: ä¸€èˆ¬ç¤¾å›£æ³•äººWaffle Co-founder. ITæ¥­ç•Œã®å¤šæ§˜æ€§ã‚„ã‚¸ã‚§ãƒ³ãƒ€ãƒ¼ã‚®ãƒ£ãƒƒãƒ—ã«ã¤ã„ã¦èªã£ã¦ã¾ã™ï¼å¥³å­ã®æµ·å¤–ç•™å­¦&ç†ç³»é€²è·¯å¿œæ´ğŸ™ŒAIã®å€«ç†ã«ã‚‚èˆˆå‘³ã‚ã‚Šã€‚ # add description
social-twitter: AsumiWaffle # add your Twitter handle
# social-facebook: # add your Facebook handle
# social-github: artemsheludko # add your Github handle
social-linkedin: asumisaito # add your Linkedin handle
social-email: a.saitou@waffle-waffle.org # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
# analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
